### ISSUE TITLE
Make shorter files on remote server

### ISSUE THREAD

**Issue by ntropy25** [lukaaash/sftp-ws#5]
Hi!
I appreciate your great work.
I’ve tested the web-client sample for several machine environments.
On local machine or on server on LAN, it works great.
But, soon I found that if the server is located remotely on the internet, the length of the uploaded files is simply shorter than the originals.
For example, if I uploaded 490,744 bytes file, it made 393,216 bytes file.
I found that the end of the file was missing.
26,253,806 bytes file made 26,181,632 bytes and still end of the file was truncated.
Do you have any idea?

**Comment by lukaaash** [comment]
Hi, many thanks for reporting this!

It was caused by a bug in Blob-based data reader - it got handling 'readable' state quite wrong, and due to lack of any automated browser-based tests, it went unnoticed for a long time. I'm not actively using the browser-based client myself _yet_...

I tried [fixing it](https://github.com/lukaaash/sftp-ws/commit/b70e56b2638ffaf3ce508a4060ead198dfece281) and now it seems to working properly - please update to the current version and give it a try.

I will test this more thoroughly myself tomorrow as well.

**Comment by ntropy25** [comment]
Thank you very much for the fast reply.
I'll try on Monday.

Thank you.

**Comment by ntropy25** [comment]
Thank you very much for the fast reply.
I've tried new version.
(npm update sftp-ws or remove and install it again and rebuild from the source)
But, sadly the symptom is the same.

**Comment by ntropy25** [comment]
Oh!
It works.

I didn't change //nuane.com/sftp-plus/sftp-0.7.0.min.js" to
//nuane.com/sftp-plus/sftp-0.7.1.min.js

Sorry.
And thank you again.
